### PR TITLE
Add container helpers that allow build to copy the CI jobs.

### PR DESCRIPTION
**Pull request by lucteo**
These containers allow use to build, as in CI job, with gcc11 the following modes:
- Debug
- Release
- address sanitizer
- thread sanitizer

### CODE REVIEW

**Comment by ericniebler** [comment]
Q: when would i want to use this?

**Comment by trxcllnt** [comment]
Why not run the containers directly?
```shell
docker run --rm -it \
  -u coder \
  -w /home/coder/stdexec \
  -v "$(pwd):/home/coder/stdexec" \
  rapidsai/devcontainers:24.04-cpp-gcc11-cuda12.4-ubuntu22.04 \
  bash -lic '\
    cmake -S . -B /tmp/build -GNinja -DCMAKE_CXX_FLAGS=-fsanitize=address -DSTDEXEC_ENABLE_TBB=OFF \
 && cmake --build /tmp/build \
 && ctest --test-dir /tmp/build --output-on-failure'
```

**Comment by ericniebler** [comment]
@lucteo I'm closing this. Let me know if there is something here I've overlooked.

**Pull request closed without merging**
