### PR TITLE
Update `ci.{c,g}pu.yml` and devcontainers to clang18, CUDA 12.4, and nvhpc24.3

### PR DESCRIPTION
**Pull request by trxcllnt**
* update `ci.cpu.yml` to cuda12.4
* update `ci.gpu.yml` to clang18-cuda12.0, clang18-cuda12.4, and nvhpc24.3
* devcontainers to clang18-cuda12.0, clang18-cuda12.4, and nvhpc24.3

### CODE REVIEW

**Comment by ericniebler** [comment]
Thank you! Do you know if this will fix the gcc-11 Release ASAN build? It's been suffering from a weird linker error for weeks.

**Comment by trxcllnt** [comment]
> Do you know if this will fix the gcc-11 Release ASAN build?

I don't know, but we'll see here shortly. We can also try other versions of GCC if we need.

**Comment by trxcllnt** [comment]
@ericniebler I think it's just complaining because I put `[skip ci]` in the last commit. This PR should be good to merge.

**Pull request merged**
