### PR TITLE
Seuqence item types

### PR DESCRIPTION
**Pull request by maikel**
Hi, this change puts the types of senders produced by a sequence into a separate typedef. I've put it into an extra PR to show where it makes a difference.

Now we have a semantic change of `completion_signatures` of a sequence-sender. It now lists the possible completion signatures of the whole sequence operation. Before this change, it was the union of all possible completions of all item operations.

### CODE REVIEW

**Comment by maikel** [comment]
@kirkshoop any thoughts about exposing input sender types of calls to `set_next(rcvr, sender)`? In the current design I fail to compute the correct completion signatures in case of customizations.

**Comment by ericniebler** [comment]
Lovely.

**Pull request merged**
