### PR TITLE
Improve EDG detection and workarounds

### PR DESCRIPTION
**Pull request by vasama**
* Add missing const in `sender_adaptor_closure`.
* Detect NVHPC as EDG first, add separate detection of NVHPC.
* Convert most NVHPC workaround conditions to check for EDG instead.
* Add detection of Visual Studio Intellisense (EDG).
* Add separate detection of the MSVC headers for Intellisense.
* Add workaround for Intellisense issue in `sender_adaptor_closure`.
* Add workarounds for EDG bugs that cropped up related to coroutines.
  It seems that currently the coroutine tests are not built in CI with EDG, because NVC++ is the only EDG based compiler and does not have coroutine support.

There is still an issue in `test_task.cpp` that I haven't been able to figure out. Once that's sorted as well, it would be nice to have another EDG-based compiler in CI, especially one with coroutine support.

### CODE REVIEW

**Comment by ericniebler** [comment]
thanks @vasama !

**Comment by ericniebler** [comment]
Do you know if the pack indexing problem is my bug or clang's?

**Comment by vasama** [comment]
I reported the suspected Clang bug here: https://github.com/llvm/llvm-project/issues/116105

**Pull request merged**
