### PR TITLE
Store 'split' sender in shared state

### PR DESCRIPTION
**Pull request by ccotter**
I was looking to get a version of "split" working on top of libunifex, but found the reference implementation of `split` here did not allow me to fork a `unifex::task` (e.g., as with the example in https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2300r5.html#design-forkable).

I didn't quite follow https://github.com/brycelelbach/wg21_p2300_std_execution/issues/466 as I'm not sure I fully understand what environments are, but I can look into that approach as well.

### CODE REVIEW

**Comment by ericniebler** [comment]
> I didn't quite follow #466 as I'm not sure I fully understand what environments are, but I can look into that approach as well.

An environment is basically just a bag of queryable properties. Today, all sender queries are queries on the sender itself. I think what I was suggesting in #446 is that have _one_ sender query: `get_env(sndr)`, and all of the other sender queries then become queries on the sender's environment. 

In that world, `split()` would store a `variant<InputSender, env_of_t<InputSender>>` in the shared state which initially stores the input sender. When `connect`-ing the input sender, the sender's environment is saved in a local, which is then moved into the `variant`, destroying the input sender.

Every copy of the `split()` sender would hold a strong reference to the shared state. Queries on those senders' environments would forward to the `variant` in the shared state.

In this way, move-only and single-shot senders could be supported while also preserving the ability of issuing sender queries on the resulting `split()` senders.

**Comment by ccotter** [comment]
Thanks for the explanation. I understand this better now.

When we preserve the value sent by the input sender, the returned split sender sends `const&` lvalues - which is the necessary sort of "hoisting" required to make a move-only sender value accessible by multiple consumers. It's not clear how sender queries could be "hoisted" or changed to provide forwarded queries in a generic way, even with a sender environment concept. I suppose the similar notion of *const lvalue*-ifying the sender environment could work?

**Comment by ericniebler** [comment]
I think we would have to treat queries like the values and errors of a single-shot sender: on the first call to fetch that value, cache it in the operation state and return a `const&` to the cached value. We could avoid doing that if the query is already returning a reference.

The problem with this approach is that there is no way to enumerate the set of sender queries, and thus no way to compute how big of a cache the operation state needs to cache the results of the queries.

**Comment by ccotter** [comment]
Thanks for explaining! My curiosity is satisfied.

**Comment by ericniebler** [comment]
I'm curious why you closed this.

**Comment by ccotter** [comment]
Ah, I should have asked instead of assuming - where do we see a `split` that can support move only input senders, one where there are the deficiencies with sender queries as noted above? Would that still be useful in the meantime? I'll reopen as a draft for the time being, and with some more clarity, I'm happy to work to evolve this change to document what's supported (and not) via tests, etc.

**Comment by msimberg** [comment]
Do I understand correctly that with this both senders and receivers would be environment providers? Would there be differences in the kinds of environments they provide or would they both be just "bags of things that can be queried"?

> I think we would have to treat queries like the values and errors of a single-shot sender: on the first call to fetch that value, cache it in the operation state and return a `const&` to the cached value. We could avoid doing that if the query is already returning a reference.
> 
> The problem with this approach is that there is no way to enumerate the set of sender queries, and thus no way to compute how big of a cache the operation state needs to cache the results of the queries.

I'm not sure if I'm misunderstanding, but are there cases where it wouldn't be enough to only store the environment of the wrapped sender in the shared state and then `get_env(split_sender)` simply returns a (possibly const) reference to that environment? Queries from successor senders would then be done on the reference to that environment. In other words, I'm missing why the individual queries would have to be cached rather than the environment as a whole?

Finally, I've seen mentions of moving away from customization based on `get_completion_scheduler`. Does that reduce the need for getting an environment from a sender? Probably does not remove the need though since there can be user-defined queries on senders...

**Comment by ericniebler** [comment]
@ccotter the committee is moving ahead with putting the sender queries into a separate "attributes" object, which changes how this issue will be fixed. Feel like taking a crack at that change first? See brycelelbach/wg21_p2300_execution#17 for the details.

**Comment by ccotter** [comment]
Will do!

**Comment by ericniebler** [comment]
Hi @ccotter, I'm closing this PR for now. I expect you'll want to fix this issue in a new PR as part of integrating the `get_attrs` changes.

**Pull request closed without merging**
