### PR TITLE
fix `when_all` and `async_scope::spawn_future` with correct initialization order

### PR DESCRIPTION
**Pull request by zyctree**
Yet it will forever wait on `sync_wait(std::move(allDone));`

I'm not sure these `on(sch, ...)` are needed, or it is a bug inside `when_all`. 
A more simple case, `sync_wait(when_all(scope.spawn_future(...)));` will never return.

### CODE REVIEW

**Comment by ericniebler** [comment]
Interesting. When I build with clang, the scope example runs fine for me. But when compiled with gcc, I see the hand you're talking about. @kirkshoop can you weigh in on why this hangs?

**Comment by kirkshoop** [comment]
it hangs in `in_place_stop_source::__try_lock_unless_stop_requested_`

the inner loop never sees an `__old_state_ == 0`

Not too familiar with this code, it could be a lifetime issue or a bug in the inplace_stop_source or a bug in the godegen..

**Comment by zyctree** [comment]
with release build, it hangs; with debug build, it runs fine
i'm using 'Apple clang version 14.0.0'

**Comment by lewissbaker** [comment]
Generally, stop-callbacks on the receiver's stop token shouldn't be registered until start() is called on the op state, although I don't think we have actually codified this guideline anywhere.

But good find! We should do a more general audit of algorithms to make sure child op states appear ss the last data members in all algorithms.

**Comment by kirkshoop** [comment]
Maybe inplace_stop_source can add some validity checks for the state to report rather than hang?

It would be nice if private constructors for inplace_stop_source and a make function would force users to add explicit construction of the members that would show that it was being used before it was constructed.

**Pull request merged**
